- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ ec2packages }}"
  become: yes

- name: Enable and start Snapd
  systemd:
    name: snapd
    state: started
    enabled: True
  become: yes

- name: Setup snapd
  shell: ln -s /var/lib/snapd/snap /snap
  become: yes

- name: Update snapd
  shell: snap install core; snap refresh core
  become: yes

- name: Install Certbot
  shell: snap install --classic certbot
  become: yes

- name: Perpare Certbot
  shell: ln -s /snap/bin/certbot /usr/bin/certbot
  become: yes

- name: Install golang
  unarchive:
    src: "https://golang.org/dl/go{{ goversion }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes
  become: yes

- name: Add Golang bin to PATH in .bash_profile
  lineinfile: 
    dest: "~/.bash_profile" 
    line: 'export PATH=$PATH:/usr/local/go/bin'
    insertafter: 'EOF'
    state: present
