source: https://gml.noaa.gov/aftp/products/trends/co2/co2_weekly_mlo.csv
header_keys: 
  - year
  - month
  - day
  - decimal
  - average
  - ndays
  - one_yr_ago
  - ten_yrs_ago
  - inc_since_1800
ignore_symbol: '#'