name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: apiserver
  IMAGE_TAG: latest
  REGISTRY: ghcr.io

defaults:
  run:
    working-directory: ./api/apiserver/

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./api/apiserver/Containerfile
        push: true
        tags: ${{ env.IMAGE_TAG }}
