name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
    
    - name: context
      run: ls -al

    - name: Build
      run: go build -o planetpulse -v ./api/apiserver/cmd/planetpulse/
